---
defaults:
  - wandb: defaults
  - hydra: defaults
  - _self_
general:
  device: 0
  random_seed: 0
data:
  fov: 47.17998034148662
  input_images: 1
  znear: 0.01
  zfar: 100.0
  category: hands
  dataset_type: MIRAGE
  with_background: false
  white_background: true
  depth_rendering: false
  ray_embedding: false
  random_background_color: false 
  training_resolution: 256
  num_training_images: 15
  cropped: false
  cam_data_path: '/home/perrettde/Documents/thesis/DATA/Manus_Data/optim_params.txt'

opt:
  iterations: 900001
  base_lr: 0.000005 # important dont fuck with!
  batch_size: 1 #32
  betas:
    - 0.9
    - 0.999
  loss: l2
  lambda_lpips: 0.01
  start_lpips_after: 800001
  pretrained_ckpt: null
  step_lr_at: 800001
  alpha_loss: true
  alpha_loss_coefficient: 0.01
  offset_penalty: true

model:
  opacity_scale: 1.0
  opacity_bias: -2.0
  scale_bias: 0.02
  scale_scale: 0.003
  xyz_scale: 0.01 # affects offset from mano verts
  xyz_bias: 0.0

logging:
  ckpt_iterations: 50000
  val_log: 10000
  loss_log: 10
  loop_log: 1000
  render_log: 10000